## week03_retail_cleaning_validation.ipynb

In [1]:
#import libraries
import pandas as pd
import numpy as np

In [2]:
#upload data and see how many columns and rows are in the dataset
df = pd.read_csv("data/retail_store_sales.csv")
df.shape

(12575, 11)

In [3]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [4]:
#info about columns and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.1+ MB

In [5]:
#check for null values
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [6]:
#check for diplicates
df.duplicated().sum()

np.int64(0)

In [7]:
#describe the dataset
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [8]:
#check unique values in object columns
for col in df.select_dtypes(include='object').columns:
    print(col, "→", df[col].unique()[:10])
    print()

Transaction ID → <StringArray>
['TXN_6867343', 'TXN_3731986', 'TXN_9303719', 'TXN_9458126', 'TXN_4575373',
 'TXN_7482416', 'TXN_3652209', 'TXN_1372952', 'TXN_9728486', 'TXN_2722661']
Length: 10, dtype: str

Customer ID → <StringArray>
['CUST_09', 'CUST_22', 'CUST_02', 'CUST_06', 'CUST_05', 'CUST_07', 'CUST_21',
 'CUST_23', 'CUST_25', 'CUST_14']
Length: 10, dtype: str

Category → <StringArray>
[                        'Patisserie',                      'Milk Products',
                           'Butchers',                          'Beverages',
                               'Food',                          'Furniture',
      'Electric household essentials', 'Computers and electric accessories']
Length: 8, dtype: str

Item → <StringArray>
[ 'Item_10_PAT', 'Item_17_MILK',  'Item_12_BUT',  'Item_16_BEV',
  'Item_6_FOOD',            nan,  'Item_1_FOOD',  'Item_16_FUR',
  'Item_22_BUT',   'Item_3_BUT']
Length: 10, dtype: str

Payment Method → <StringArray>
['Digital Wallet', 'Credit Card', 'Cash']
Length: 3, dtype: str

Location → <StringArray>
['Online', 'In-store']
Length: 2, dtype: str

Transaction Date → <StringArray>
['2024-04-08', '2023-07-23', '2022-10-05', '2022-05-07', '2022-10-02',
 '2023-11-30', '2023-06-10', '2024-04-02', '2023-04-26', '2024-03-14']
Length: 10, dtype: str

Discount Applied → [True False nan]

C:\Users\hp\AppData\Local\Temp\ipykernel_9220\1810523624.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

In [9]:
#check unique values in Discount Applied column
df['Discount Applied'].unique()

array([True, False, nan], dtype=object)

In [10]:
#check for null values in Price Per Unit, Quantity, and Total Spent columns
df[df['Price Per Unit'].isnull() | df['Quantity'].isnull() | df['Total Spent'].isnull()].head(10)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,2025-01-13,False
21,TXN_8685338,CUST_15,Milk Products,NaN,NaN,3.0,105.0,Credit Card,In-store,2023-10-29,NaN
25,TXN_3481599,CUST_05,Furniture,NaN,39.5,NaN,NaN,Cash,Online,2022-09-08,False
32,TXN_1543244,CUST_20,Food,NaN,NaN,8.0,196.0,Credit Card,Online,2024-10-25,True
34,TXN_1621497,CUST_06,Patisserie,NaN,23.0,NaN,NaN,Cash,In-store,2023-02-18,NaN

In [11]:
#check for null values in Transaction Date column
df['Transaction Date'].head()

0    2024-04-08
1    2023-07-23
2    2022-10-05
3    2022-05-07
4    2022-10-02
Name: Transaction Date, dtype: str

In [12]:
#clean dataset with cleaning function script
from cleaning_functions import clean_dataset

df_clean = clean_dataset(df)
df_clean.info()

Dropped 604 rows with unrecoverable missing values.
<class 'pandas.DataFrame'>
Index: 11971 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    11971 non-null  str
 1   Customer ID       11971 non-null  str
 2   Category          11971 non-null  str
 3   Item              11971 non-null  str
 4   Price Per Unit    11971 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    11971 non-null  str
 8   Location          11971 non-null  str
 9   Transaction Date  11971 non-null  datetime64[us]
 10  Discount Applied  11971 non-null  object
dtypes: datetime64[us](1), float64(3), object(1), str(6)
memory usage: 1.1+ MB

In [13]:
#check for null values in Price Per Unit, Quantity, and Total Spent columns
missing_count = df[['Price Per Unit', 'Quantity', 'Total Spent']].isnull().sum(axis=1)
missing_count.value_counts()

0    11362
1      609
2      604
Name: count, dtype: int64

In [14]:
#check after cleaning
df_clean.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [15]:
df_clean.duplicated().sum()

np.int64(0)

In [16]:
df_clean.dtypes

Transaction ID                 str
Customer ID                    str
Category                       str
Item                           str
Price Per Unit             float64
Quantity                   float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
Discount Applied            object
dtype: object

In [17]:
df_clean[['Price Per Unit', 'Quantity', 'Total Spent']].describe()

       Price Per Unit      Quantity   Total Spent
count    11971.000000  11971.000000  11971.000000
mean        23.360872      5.536380    129.652577
std         10.741889      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [18]:
#make sure the equation Price Per Unit * Quantity = Total Spent is correct
check = (df_clean['Price Per Unit'] * df_clean['Quantity']).round(2)
mismatch = (check != df_clean['Total Spent'].round(2)).sum()
print(f"number of mismatched rows: {mismatch}")

number of mismatched rows: 0

In [19]:
before_after = pd.DataFrame({
    "Metric": [
        "Total rows",
        "Missing - Item",
        "Missing - Price Per Unit",
        "Missing - Quantity",
        "Missing - Total Spent",
        "Missing - Discount Applied",
        "Duplicate rows"
    ],
    "Before": [
        len(df),
        df['Item'].isnull().sum(),
        df['Price Per Unit'].isnull().sum(),
        df['Quantity'].isnull().sum(),
        df['Total Spent'].isnull().sum(),
        df['Discount Applied'].isnull().sum(),
        df.duplicated().sum()
    ],
    "After": [
        len(df_clean),
        df_clean['Item'].isnull().sum(),
        df_clean['Price Per Unit'].isnull().sum(),
        df_clean['Quantity'].isnull().sum(),
        df_clean['Total Spent'].isnull().sum(),
        df_clean['Discount Applied'].isnull().sum(),
        df_clean.duplicated().sum()
    ]
})
before_after

                       Metric  Before  After
0                  Total rows   12575  11971
1              Missing - Item    1213      0
2    Missing - Price Per Unit     609      0
3          Missing - Quantity     604      0
4       Missing - Total Spent     604      0
5  Missing - Discount Applied    4199      0
6              Duplicate rows       0      0